### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by shuvashish76** [aivanovski/kpassnotes#231]
### Overview

App crashing when simply installed & open it.

### Logs:

```
FATAL EXCEPTION: main
Process: com.ivanovsky.passnotes, PID: 23718
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ivanovsky.passnotes/com.ivanovsky.passnotes.presentation.main.MainActivity}: java.lang.IllegalStateException: Invalid launcher type: type=com.ivanovsky.passnotes.presentation.main.ActivityResultManager$LauncherType$AllFilesPermission@a2bfa6a, minSdk=28
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Invalid launcher type: type=com.ivanovsky.passnotes.presentation.main.ActivityResultManager$LauncherType$AllFilesPermission@a2bfa6a, minSdk=28
	at com.ivanovsky.passnotes.presentation.main.ActivityResultManager.registerLauncher(ActivityResultManager.kt:56)
	at com.ivanovsky.passnotes.presentation.main.ActivityResultManager.onCreate(ActivityResultManager.kt:27)
	at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:24)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
	at androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(ReportFragment.kt:192)
	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.kt:87)
	at androidx.lifecycle.ReportFragment.onActivityCreated(ReportFragment.kt:50)
	at android.app.Fragment.performActivityCreated(Fragment.java:2531)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1318)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2998)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:182)
	at android.app.Activity.performCreate(Activity.java:7151)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 11 more
```

### How to reproduce

Simply launch the app after installation.

### Version

1.3.0

### Android Version

9

### Device Model

Lenovo Tab4 8 Plus

**Comment by aivanovski** [comment]
Thanks for report. It will be fixed in v1.3.1, you may download app with fix from FDroid in a couple of days on directly from CI page https://github.com/aivanovski/kpassnotes/actions/runs/7861710811
@shuvashish76
